import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>umeco&apos;s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col items-center justify-center">
          <div className="flex flex-col items-center justify-center md:w-1/2">
            <img
              className="rounded-full  w-40 h-40 mt-24"
              src="my_face.jpeg"
              alt="face_img"
            ></img>
            <p className="text-4xl pt-4">梅本 晴弥</p>
            <p className="text-xl text-gray-400 pt-1 pb-4">ML Engineer</p>

            <div className="flex flex-row justify-center pb-4">
              <a
                href="https://www.linkedin.com/in/umeco/"
                target="_blank"
                className="p-1"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  className="transform w-8 h-8 hover:fill-blue-500 hover:scale-125"
                >
                  <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                </svg>
              </a>
              <a
                href="https://github.com/umepy"
                target="_blank"
                className="p-1"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  className="transform w-8 h-8 hover:fill-blue-500 hover:scale-125"
                >
                  <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                </svg>
              </a>
              <a
                href="https://booklog.jp/users/umecoco"
                target="_blank"
                className="p-1"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill-rule="evenodd"
                  clip-rule="evenodd"
                  viewBox="0 0 24 24"
                  className="transform w-8 h-8 hover:fill-blue-500 hover:scale-125"
                >
                  <path d="M22 24h-17c-1.657 0-3-1.343-3-3v-18c0-1.657 1.343-3 3-3h17v24zm-2-4h-14.505c-1.375 0-1.375 2 0 2h14.505v-2zm0-18h-3v9l-2-1.547-2 1.547v-9h-8v16h15v-16z" />
                </svg>
              </a>
              <a
                href="https://speakerdeck.com/umeco"
                target="_blank"
                className="p-1"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  className="transform w-8 h-8 hover:fill-blue-500 hover:scale-125"
                >
                  <path d="M16.488 20l3.414 4h-2.627l-3.42-4h2.633zm1.512-14h-4v1h4v-1zm-7 18h2v-4h-2v4zm-6.918 0h2.628l3.42-4h-2.633l-3.415 4zm13.918-16h-4v1h4v-1zm0 2h-4v1h4v-1zm-8.5 3c1.762 0 3.205-1.306 3.45-3h-3.95v-3.95c-1.694.245-3 1.688-3 3.45 0 1.933 1.567 3.5 3.5 3.5zm.5-6.95v2.95h2.95c-.221-1.529-1.421-2.729-2.95-2.95zm8 5.95h-4v1h4v-1zm5-9h-1v15h-20v-15h-1v-3h22v3zm-3 0h-16v13h16v-13z" />
                </svg>
              </a>
            </div>

            <p className="text-3xl text-text_gray">Biography</p>
            <p className="text-xl text-text_gray">
              学部２年生から機械学習に興味を持ち、データマイニングや機械学習を専門的に扱う大原研究室へラボワーク生として参加。学部３年生からは理工学部高度実践生（学科初）として正式に研究室に所属し、データ分析コンペティションや研究会への参加から機械学習全般への理解を深める。学部４年生では、データ分析コンペティションでの上位入賞を果たし、代替食材に関する研究を行った。大学院では、強化学習分野において埋め込みモデルを応用させた学習手法を研究した．
            </p>
          </div>
        </div>
        <div className="bg-gray-100">
          <p className="text-3xl text-text_gray">Carrier</p>
        </div>
      </main>
    </>
  );
}
