name: Build Test
on:
  push:
   branches-ignore:
     - main
     - development

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v3

     - name: setup-node
       uses: actions/setup-node@v3
       with:
         node-version: 18
         cache: npm

     - name: npm-install
       run: npm i

     - name: app-build
       run: npm run build