name: Deploy to Firebase
on: push

jobs:
  deploy-to-firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: install firebase-tools
        run: npm install -g firebase-tools
      
      - name: deploy to firebase
        run: firebase deploy --token ${{secrets.FIREBASE_TOKEN}}